import { QUALITY_CHECK_KEYS, QUALITY_CHECK_LABELS } from "@/lib/assessment/qualityChecks";
import { buildTextPdfBytes } from "@/lib/files/textPdf";
import type { PublicShareReport } from "./publicReport";

function readinessLabel(score: number): string {
  if (score >= 75) return "Ready";
  if (score >= 50) return "Developing";
  return "Needs work";
}

function pad(label: string, width: number): string {
  return label.length >= width ? label.slice(0, width) : `${label}${" ".repeat(width - label.length)}`;
}

export function buildStudentReportText(report: PublicShareReport): string {
  const score = report.score ?? 0;
  const lines: string[] = [
    "CALIBER  |  STUDENT CV REPORT",
    "============================================================",
    "This report is for the student. Share the link or this PDF.",
    "",
    `${pad("Student:", 14)}${report.candidateName}`,
    `${pad("Goal:", 14)}${report.goalTitle}${report.goalCode ? ` (${report.goalCode})` : ""}`,
    `${pad("File:", 14)}${report.fileName}`,
    `${pad("Date:", 14)}${new Date(report.generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}`,
    "",
    "OVERALL GRADE",
    "------------------------------------------------------------",
    `${pad("Letter grade:", 16)}${report.grade || "—"}`,
    `${pad("Score:", 16)}${score} / 100`,
    `${pad("Readiness:", 16)}${readinessLabel(score)}`,
  ];

  if (report.reason) {
    lines.push("", report.reason);
  }

  lines.push("", "QUALITY CHECKS  (each scored 0-100)", "------------------------------------------------------------");
  if (report.qualityChecks) {
    for (const key of QUALITY_CHECK_KEYS) {
      const item = report.qualityChecks[key];
      lines.push(`${pad(QUALITY_CHECK_LABELS[key], 16)}${pad(String(item.score), 6)}${item.evidence}`);
    }
    lines.push("", `${pad("Quality average:", 16)}${report.qualityAverage ?? "—"} / 100`);
  } else {
    lines.push("Quality checks were not available for this assessment. Re-score the CV to generate them.");
  }

  if (report.goalFit) {
    lines.push("", "GOAL FIT", "------------------------------------------------------------");
    lines.push(`${pad("CV quality:", 16)}${report.goalFit.profile_quality}   (40%)`);
    lines.push(`${pad("Focus skills:", 16)}${report.goalFit.focus_skills}   (35%)`);
    lines.push(`${pad("Goal context:", 16)}${report.goalFit.context_alignment}   (25%)`);
  }

  if (report.matchedSkills.length || report.missingSkills.length) {
    lines.push("", "SKILLS", "------------------------------------------------------------");
    if (report.matchedSkills.length) lines.push(`Matched: ${report.matchedSkills.join(", ")}`);
    if (report.missingSkills.length) lines.push(`Missing: ${report.missingSkills.join(", ")}`);
  }

  if (report.recommendations.length) {
    lines.push("", "RECOMMENDATIONS", "------------------------------------------------------------");
    report.recommendations.forEach((rec, index) => {
      lines.push(`${index + 1}. [${rec.priority.toUpperCase()}] ${rec.title}`);
      if (rec.detail) lines.push(`   ${rec.detail}`);
    });
  }

  const content = report.dimensions.filter((d) => !(QUALITY_CHECK_KEYS as readonly string[]).includes(d.key));
  if (content.length) {
    lines.push("", "CONTENT AREAS", "------------------------------------------------------------");
    for (const dim of content) {
      lines.push(`${pad(dim.label, 16)}${pad(String(dim.score), 6)}${dim.evidence || ""}`.trimEnd());
    }
  }

  if (report.highlights.length) {
    lines.push("", "STRENGTHS", "------------------------------------------------------------");
    for (const item of report.highlights) lines.push(`- ${item}`);
  }
  if (report.redFlags.length) {
    lines.push("", "GAPS", "------------------------------------------------------------");
    for (const item of report.redFlags) lines.push(`- ${item}`);
  }

  lines.push(
    "",
    "------------------------------------------------------------",
    "Generated by Caliber Higher Ed. This is career-readiness feedback,",
    "not a hiring decision.",
  );

  return lines.join("\n");
}

export function buildStudentReportPdf(report: PublicShareReport): Uint8Array {
  return buildTextPdfBytes(buildStudentReportText(report), 52);
}
